name: CI/CD pipeline for peloTeo Backend

on:
  pull_request:
    branches:
      - prod

jobs:
  install:
    name: Install
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install

  build_and_upload:
    runs-on: ubuntu-20.04
    needs: [install]
    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: peloteo
          password: password123

      - name: Create docker image and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: peloteo/peloteo_back:latest
